import { ContentSections } from "../types";

export const content: ContentSections = {
  home: [
    "Welcome to my Neovim-inspired portfolio!",
    "Use 'hjkl' (or arrow keys) to navigate",
    "Use ':' to open the command line",
    "Type a section name (home, about, projects, skills, contact) and press Enter to navigate",
    "Use ':theme' to change themes",
    " ",
    "Vim commands:",
    "w - move forward by word",
    "b - move backward by word",
    "^ - move to start of line",
    "$ - move to end of line",
    "gg - move to top of file",
    "G - move to bottom of file",
  ],
  about: [
    "About Me",
    " ",
    "I'm a passionate developer with a love for Vim and terminal-based applications.",
    "Currently pursuing an Honors Bachelor of Science in Computer Science at the University of Toronto.",
    "I specialize in software engineering, front-end development, and API design.",
    "My work demonstrates a focus on clean, efficient, and scalable solutions.",
    "I enjoy contributing to open-source projects and mentoring aspiring developers.",
  ],
  projects: [
    "Projects",
    " ",
    "1. StudyBuddies",
    "   - A Go-powered app enabling real-time location tracking and messaging for study sessions.",
    "   - Integrated PostgreSQL for secure and efficient data management.",
    "   - Utilized WebSocket for seamless user communication.",
    " ",
    "2. Personal Portfolio Website",
    "   - Built with NextJS, TailwindCSS, and Go for showcasing technical expertise.",
    "   - Includes a custom CMS for managing dynamic content.",
    "   - Features a dynamic Articles section highlighting my industry insights.",
    " ",
    "3. Stack Selector",
    "   - A web application for recommending technology stacks based on project needs.",
    "   - Leveraged Go and MongoDB for a robust backend.",
    "   - Designed a responsive frontend with HTMX for real-time updates.",
    " ",
    "4. ShopTrack",
    "   - Android e-commerce app for store owners and shoppers.",
    "   - Built with Java and Firebase for robust order processing.",
  ],
  skills: [
    "Skills",
    " ",
    "Languages:",
    "- Java, Python, C, HTML, CSS, JavaScript, TypeScript, Golang, Swift",
    " ",
    "Frameworks & Libraries:",
    "- React, NextJS, ExpressJS, NodeJS, TailwindCSS, HTMX",
    " ",
    "Developer Tools:",
    "- Vite, Git, Linux, Bash, Kubernetes, Docker",
  ],
  experience: [
    "Experience",
    " ",
    "Software Engineering Advisor - AVOLTA Inc (Aug 2024 - Present)",
    "   - Designed an API testing architecture that increased test coverage by 60%.",
    "   - Improved query performance by 30% and reduced redundancy by 20% with optimized database schemas.",
    "   - Mentored 3 interns, enhancing their efficiency and project contributions by 40%.",
    "   - Refactored APIs to improve modularity and maintainability.",
    " ",
    "Software Developer Intern - JDRF Electromag Engineering (Jan 2024 - Sep 2024)",
    "   - Implemented an automated Slack alert system, doubling team responsiveness.",
    "   - Refactored a critical software module, improving maintainability by 25%.",
    "   - Managed CI/CD pipelines, reducing deployment time by 15%.",
    "   - Achieved 90% code coverage in unit testing and reduced runtime by 30%.",
    " ",
    "Developer / Plugin Engineer - Treasurelands (Jul 2023 - Jan 2024)",
    "   - Developed and maintained 20+ Minecraft plugins, increasing player retention by 15%.",
    "   - Engineered a load-balancing proxy, improving connection speed by 30%.",
    "   - Managed databases for 10,000+ players, optimizing performance and stability.",
    "   - Boosted plugin performance by 25% with new technology integrations.",
  ],
  contact: [
    "Contact",
    " ",
    "Email: damian@damian717.com",
    "GitHub: github.com/example",
    "LinkedIn: linkedin.com/in/example",
    "Portfolio: damian717.com",
    " ",
    "Feel free to reach out for collaborations, job opportunities, or just to chat about tech!",
  ],
};
